# 1. DATABASE MYSQL CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/ql010226?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=tri1912
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. HIBERNATE / JPA CONFIG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. DESKTOP APP (SWING) CONFIG
spring.main.web-application-type=none